export type QuestionDemoKind =
  | "choice"
  | "text"
  | "ranking"
  | "matching"
  | "fill"
  | "drag"
  | "hotspot"
  | "slider"
  | "stars"
  | "nps";

export type QuestionTypePage = {
  slug: string;
  title: string;
  navTitle: string;
  mode: "Quiz" | "Sondage" | "Quiz et sondage";
  description: string;
  detail: string;
  question: string;
  instruction: string;
  options: string[];
  demoKind: QuestionDemoKind;
  image: string;
  imageAlt: string;
  bestFor: { title: string; text: string }[];
  capabilities: { title: string; text: string }[];
  tips: string[];
  related: string[];
};

export const QUESTION_TYPE_PAGES: QuestionTypePage[] = [
  {
    slug: "multiple-choice",
    title: "Question à choix multiple",
    navTitle: "Choix multiple",
    mode: "Quiz et sondage",
    description: "Proposez plusieurs réponses et mesurez immédiatement ce que le groupe sait ou pense.",
    detail: "Le choix multiple s’adapte à l’évaluation comme au sondage. Dans un quiz, vous désignez la ou les bonnes réponses. Dans un sondage, chaque option devient un signal à analyser.",
    question: "Quel comportement protège le mieux un mot de passe ?",
    instruction: "Sélectionnez une réponse.",
    options: ["Activer la double authentification", "Le noter sur un post-it", "Le partager avec son équipe", "Le réutiliser partout"],
    demoKind: "choice",
    image: "/images/brivia-learner-session.jpg",
    imageAlt: "Un apprenant répond à une activité numérique pendant une formation",
    bestFor: [
      { title: "Vérifier une notion", text: "Contrôlez rapidement la compréhension avant de poursuivre." },
      { title: "Faire voter", text: "Donnez au groupe des options claires et comparables." },
      { title: "Diagnostiquer", text: "Utilisez des distracteurs crédibles pour repérer les confusions." },
    ],
    capabilities: [
      { title: "Une ou plusieurs réponses", text: "Adaptez la règle à la question posée." },
      { title: "Ordre maîtrisé", text: "Conservez ou mélangez l’ordre des propositions." },
      { title: "Temps et points", text: "Ajoutez un chronomètre et un barème pour le mode quiz." },
      { title: "Correction lisible", text: "Révélez la bonne réponse au moment choisi." },
    ],
    tips: ["Écrivez des options de longueur proche.", "Évitez les indices grammaticaux.", "Limitez-vous à quatre réponses lorsque c’est possible."],
    related: ["true-false", "single-choice", "short-answer"],
  },
  {
    slug: "true-false",
    title: "Question vrai ou faux",
    navTitle: "Vrai ou faux",
    mode: "Quiz",
    description: "Testez une affirmation en un geste et ouvrez immédiatement la discussion.",
    detail: "Le format vrai ou faux est utile pour lancer une séquence, faire émerger une idée reçue ou vérifier un principe simple sans ralentir la session.",
    question: "Une sauvegarde cloud remplace toujours une stratégie de sauvegarde complète.",
    instruction: "Choisissez votre réponse.",
    options: ["Vrai", "Faux"],
    demoKind: "choice",
    image: "/images/brivia-workshop-hero.jpg",
    imageAlt: "Un formateur échange avec son groupe pendant une session interactive",
    bestFor: [
      { title: "Casser une idée reçue", text: "Exposez une affirmation qui mérite une explication." },
      { title: "Démarrer vite", text: "Obtenez une première participation sans effort cognitif inutile." },
      { title: "Vérifier un principe", text: "Validez une règle simple avant un exercice plus riche." },
    ],
    capabilities: [
      { title: "Deux réponses nettes", text: "Le participant comprend immédiatement l’action attendue." },
      { title: "Correction différée", text: "Gardez le suspense jusqu’au débrief." },
      { title: "Chronomètre optionnel", text: "Installez un rythme sans rendre la réponse précipitée." },
      { title: "Résultats en direct", text: "Voyez la répartition de la salle au même instant." },
    ],
    tips: ["N’utilisez qu’une seule idée par affirmation.", "Évitez les doubles négations.", "Prévoyez une explication après la réponse."],
    related: ["multiple-choice", "short-answer", "fill-blank"],
  },
  {
    slug: "short-answer",
    title: "Question à réponse courte",
    navTitle: "Réponse courte",
    mode: "Quiz",
    description: "Demandez un mot ou une expression sans donner d’indice dans les réponses.",
    detail: "La réponse courte vérifie le rappel actif. Vous définissez la réponse attendue et pouvez accepter plusieurs formulations lorsque le vocabulaire le demande.",
    question: "Quel protocole sécurise une page web dans le navigateur ?",
    instruction: "Saisissez un mot ou une expression.",
    options: ["HTTPS"],
    demoKind: "text",
    image: "/images/brivia-quiz-authoring.jpg",
    imageAlt: "Un formateur prépare une question de quiz sur son ordinateur",
    bestFor: [
      { title: "Tester le rappel", text: "Le participant produit la réponse sans reconnaissance visuelle." },
      { title: "Vérifier un terme", text: "Contrôlez l’acquisition d’un vocabulaire précis." },
      { title: "Faire calculer", text: "Demandez un résultat court après un raisonnement." },
    ],
    capabilities: [
      { title: "Réponses acceptées", text: "Ajoutez des variantes, synonymes ou graphies valides." },
      { title: "Barème configurable", text: "Ajustez le poids de la question dans le score." },
      { title: "Temps de réponse", text: "Laissez assez de temps pour réfléchir et saisir." },
      { title: "Révision manuelle", text: "Gardez la possibilité de vérifier les cas ambigus." },
    ],
    tips: ["Précisez l’unité attendue.", "Acceptez les variantes raisonnables.", "Réservez ce format aux réponses vraiment courtes."],
    related: ["fill-blank", "open-text", "multiple-choice"],
  },
  {
    slug: "ranking",
    title: "Question de classement",
    navTitle: "Classement",
    mode: "Quiz et sondage",
    description: "Faites ordonner des étapes, des priorités ou des options selon un critère explicite.",
    detail: "Le classement peut mesurer une connaissance procédurale ou recueillir les priorités du groupe. Il rend visibles les arbitrages, pas seulement le premier choix.",
    question: "Remettez les étapes de gestion d’un incident dans l’ordre.",
    instruction: "Déplacez les éléments pour former votre ordre.",
    options: ["Détecter", "Contenir", "Corriger", "Capitaliser"],
    demoKind: "ranking",
    image: "/images/brivia-results-debrief.jpg",
    imageAlt: "Deux professionnels analysent ensemble les résultats d’une session",
    bestFor: [
      { title: "Évaluer une procédure", text: "Vérifiez que chaque étape arrive au bon moment." },
      { title: "Prioriser des besoins", text: "Faites émerger un ordre collectif exploitable." },
      { title: "Comparer des critères", text: "Observez les arbitrages entre plusieurs options." },
    ],
    capabilities: [
      { title: "Ordre correct en quiz", text: "Attribuez des points à la séquence attendue." },
      { title: "Priorités en sondage", text: "Agrégez les classements sans bonne réponse." },
      { title: "Éléments réordonnables", text: "Le geste reste direct sur ordinateur et mobile." },
      { title: "Résultat détaillé", text: "Analysez les positions données à chaque élément." },
    ],
    tips: ["Annoncez clairement le critère de classement.", "Limitez le nombre d’éléments.", "Évitez deux options presque équivalentes."],
    related: ["drag-drop", "matching", "frequency-scale"],
  },
  {
    slug: "matching",
    title: "Question d’association",
    navTitle: "Association",
    mode: "Quiz",
    description: "Reliez chaque notion à sa définition, son exemple ou sa catégorie.",
    detail: "L’association teste plusieurs liens dans une seule question. Elle convient aux vocabulaires, aux rôles, aux causes et conséquences ou aux correspondances visuelles.",
    question: "Associez chaque rôle à sa responsabilité principale.",
    instruction: "Sélectionnez une correspondance dans chaque ligne.",
    options: ["DPO : données personnelles", "RSSI : sécurité", "DSI : systèmes d’information"],
    demoKind: "matching",
    image: "/images/brivia-quiz-authoring.jpg",
    imageAlt: "Un professionnel conçoit une activité pédagogique sur ordinateur",
    bestFor: [
      { title: "Relier terme et définition", text: "Vérifiez un ensemble de concepts en une seule vue." },
      { title: "Associer rôle et mission", text: "Clarifiez les responsabilités dans une organisation." },
      { title: "Comparer cause et effet", text: "Rendez les liens logiques plus concrets." },
    ],
    capabilities: [
      { title: "Deux colonnes", text: "Structurez les éléments sources et leurs correspondances." },
      { title: "Paires validées", text: "Définissez précisément chaque association correcte." },
      { title: "Ordre flexible", text: "Mélangez les propositions pour éviter les indices." },
      { title: "Score consolidé", text: "Mesurez la réussite sur l’ensemble des paires." },
    ],
    tips: ["Utilisez des libellés courts.", "Gardez des catégories homogènes.", "Évitez une correspondance évidente par sa longueur."],
    related: ["ranking", "drag-drop", "fill-blank"],
  },
  {
    slug: "fill-blank",
    title: "Question à texte à trous",
    navTitle: "Texte à trous",
    mode: "Quiz",
    description: "Faites compléter une phrase, une règle ou un extrait avec les termes attendus.",
    detail: "Le texte à trous conserve le contexte tout en sollicitant le rappel. Plusieurs blancs peuvent être placés dans une même phrase et recevoir des variantes acceptées.",
    question: "Complétez la règle de sécurité.",
    instruction: "Saisissez le terme manquant.",
    options: ["confidentiel"],
    demoKind: "fill",
    image: "/images/brivia-learner-session.jpg",
    imageAlt: "Un participant complète une activité pendant une formation",
    bestFor: [
      { title: "Mémoriser une formulation", text: "Travaillez une définition ou une règle précise." },
      { title: "Compléter un processus", text: "Faites retrouver les éléments clés dans leur contexte." },
      { title: "Pratiquer une langue", text: "Entraînez le vocabulaire et la syntaxe." },
    ],
    capabilities: [
      { title: "Plusieurs blancs", text: "Construisez une phrase ou un paragraphe progressif." },
      { title: "Variantes acceptées", text: "Tolérez les formulations équivalentes utiles." },
      { title: "Contexte conservé", text: "Le participant répond dans une phrase lisible." },
      { title: "Correction ciblée", text: "Repérez exactement le terme qui pose problème." },
    ],
    tips: ["Ne retirez que les mots importants.", "Gardez assez de contexte.", "Acceptez les accents et variantes utiles."],
    related: ["short-answer", "matching", "multiple-choice"],
  },
  {
    slug: "drag-drop",
    title: "Question glisser-déposer",
    navTitle: "Glisser-déposer",
    mode: "Quiz",
    description: "Faites placer des éléments dans des zones pour reproduire un geste métier.",
    detail: "Le glisser-déposer transforme une consigne en manipulation. Il convient aux catégories, aux schémas, aux plans et aux séquences spatiales.",
    question: "Placez chaque action dans la bonne phase du projet.",
    instruction: "Choisissez une zone pour chaque élément.",
    options: ["Cadrage", "Production", "Validation"],
    demoKind: "drag",
    image: "/images/brivia-workshop-hero.jpg",
    imageAlt: "Une activité collective animée dans une salle de formation",
    bestFor: [
      { title: "Classer visuellement", text: "Associez des éléments à des zones ou catégories." },
      { title: "Reproduire un geste", text: "Rapprochez l’exercice de la situation réelle." },
      { title: "Travailler un schéma", text: "Faites manipuler les parties d’un système." },
    ],
    capabilities: [
      { title: "Image de fond", text: "Utilisez un plan ou un support métier." },
      { title: "Zones configurables", text: "Définissez précisément les emplacements attendus." },
      { title: "Éléments multiples", text: "Ajoutez les objets à placer et leur destination." },
      { title: "Validation complète", text: "Contrôlez toutes les positions avant correction." },
    ],
    tips: ["Utilisez une image lisible.", "Créez des zones assez grandes sur mobile.", "Limitez le nombre d’éléments simultanés."],
    related: ["hotspot", "matching", "ranking"],
  },
  {
    slug: "hotspot",
    title: "Question à zone cliquable",
    navTitle: "Zone cliquable",
    mode: "Quiz",
    description: "Demandez de repérer précisément une zone sur une image, un plan ou un document.",
    detail: "La zone cliquable évalue l’observation et la localisation. Le participant répond directement dans le support visuel, sans passer par une liste.",
    question: "Repérez la zone utilisée pour lancer la présentation.",
    instruction: "Cliquez sur la zone qui vous semble correcte.",
    options: ["Zone supérieure", "Zone centrale", "Zone inférieure"],
    demoKind: "hotspot",
    image: "/images/brivia-join-qr.jpg",
    imageAlt: "Une participante utilise son téléphone face à un support projeté",
    bestFor: [
      { title: "Lire un schéma", text: "Vérifiez qu’un élément visuel est correctement identifié." },
      { title: "Analyser une interface", text: "Faites localiser une commande ou une information." },
      { title: "Observer un document", text: "Testez l’attention à un détail significatif." },
    ],
    capabilities: [
      { title: "Image support", text: "Importez le visuel qui porte la question." },
      { title: "Zones multiples", text: "Définissez une ou plusieurs réponses valides." },
      { title: "Rayon ajustable", text: "Adaptez la précision attendue à l’usage." },
      { title: "Réponse directe", text: "Le clic devient la réponse, sans intermédiaire." },
    ],
    tips: ["Choisissez une image nette.", "Évitez les zones trop proches.", "Annoncez le niveau de précision attendu."],
    related: ["drag-drop", "matching", "true-false"],
  },
  {
    slug: "slider",
    title: "Question avec curseur",
    navTitle: "Curseur",
    mode: "Quiz",
    description: "Faites estimer une valeur sur une échelle continue avec un geste simple.",
    detail: "Le curseur est adapté aux estimations, ordres de grandeur et valeurs numériques. Vous définissez les bornes, le pas et la valeur correcte.",
    question: "Combien de minutes faut-il prévoir pour ce débrief ?",
    instruction: "Positionnez le curseur.",
    options: ["0", "60", "5"],
    demoKind: "slider",
    image: "/images/brivia-results-debrief.jpg",
    imageAlt: "Une équipe prépare le débrief des résultats d’une session",
    bestFor: [
      { title: "Estimer une valeur", text: "Faites raisonner sans imposer des options pré-écrites." },
      { title: "Tester un ordre de grandeur", text: "Vérifiez la compréhension d’une mesure." },
      { title: "Travailler une durée", text: "Demandez un temps, un coût ou une quantité." },
    ],
    capabilities: [
      { title: "Bornes libres", text: "Définissez la valeur minimale et maximale." },
      { title: "Pas configurable", text: "Choisissez la précision du déplacement." },
      { title: "Libellés de contexte", text: "Nommez les deux extrémités de l’échelle." },
      { title: "Valeur correcte", text: "Évaluez automatiquement la réponse choisie." },
    ],
    tips: ["Affichez l’unité.", "Utilisez des bornes réalistes.", "Choisissez un pas cohérent avec la précision attendue."],
    related: ["nps-scale", "likert-scale", "short-answer"],
  },
  {
    slug: "single-choice",
    title: "Sondage à choix unique",
    navTitle: "Choix unique",
    mode: "Sondage",
    description: "Recueillez une préférence nette lorsque chaque participant doit retenir une seule option.",
    detail: "Le choix unique permet de trancher rapidement entre plusieurs propositions. Il n’y a pas de bonne réponse, seulement une répartition à commenter ou utiliser pour décider.",
    question: "Quel sujet faut-il approfondir pendant la prochaine session ?",
    instruction: "Choisissez une seule proposition.",
    options: ["Mise en pratique", "Cas clients", "Méthodologie", "Questions libres"],
    demoKind: "choice",
    image: "/images/brivia-group-energy.jpg",
    imageAlt: "Un groupe participe activement à un atelier professionnel",
    bestFor: [
      { title: "Choisir un sujet", text: "Laissez le groupe orienter la suite de la session." },
      { title: "Prendre une décision", text: "Rendez visible l’option majoritaire." },
      { title: "Segmenter un public", text: "Identifiez les profils ou besoins présents." },
    ],
    capabilities: [
      { title: "Une réponse par personne", text: "Chaque vote garde le même poids." },
      { title: "Résultats instantanés", text: "La distribution apparaît pendant la session." },
      { title: "Réponses anonymes", text: "Favorisez une expression plus libre selon le contexte." },
      { title: "Export des données", text: "Conservez les choix pour l’analyse après l’atelier." },
    ],
    tips: ["Rendez les options mutuellement exclusives.", "Ajoutez une option neutre si nécessaire.", "Expliquez comment le résultat sera utilisé."],
    related: ["multiple-choice", "likert-scale", "open-text"],
  },
  {
    slug: "likert-scale",
    title: "Question à échelle de Likert",
    navTitle: "Échelle de Likert",
    mode: "Sondage",
    description: "Mesurez le niveau d’accord face à une affirmation avec une échelle équilibrée.",
    detail: "L’échelle de Likert transforme une perception en distribution lisible. Elle sert aux retours de formation, baromètres internes et diagnostics d’adhésion.",
    question: "Je me sens capable d’appliquer cette méthode dès demain.",
    instruction: "Indiquez votre niveau d’accord.",
    options: ["Pas du tout d’accord", "Pas d’accord", "Neutre", "D’accord", "Tout à fait d’accord"],
    demoKind: "choice",
    image: "/images/brivia-results-debrief.jpg",
    imageAlt: "Deux responsables formation relisent les retours d’un groupe",
    bestFor: [
      { title: "Mesurer la confiance", text: "Évaluez le sentiment de capacité avant et après." },
      { title: "Tester l’adhésion", text: "Observez l’accord avec une orientation ou une pratique." },
      { title: "Suivre une évolution", text: "Comparez les réponses entre plusieurs temps." },
    ],
    capabilities: [
      { title: "Échelle personnalisée", text: "Adaptez le nombre et le libellé des niveaux." },
      { title: "Point neutre", text: "Incluez ou retirez une position intermédiaire." },
      { title: "Distribution en direct", text: "Commentez la diversité des perceptions." },
      { title: "Analyse exportable", text: "Poursuivez le traitement après la session." },
    ],
    tips: ["Formulez une seule idée.", "Gardez une échelle symétrique.", "Utilisez toujours le même sens de lecture."],
    related: ["frequency-scale", "nps-scale", "single-choice"],
  },
  {
    slug: "frequency-scale",
    title: "Question à échelle de fréquence",
    navTitle: "Échelle de fréquence",
    mode: "Sondage",
    description: "Mesurez la régularité d’une pratique avec des réponses ordonnées de jamais à toujours.",
    detail: "L’échelle de fréquence aide à objectiver les habitudes. Elle est particulièrement utile pour les diagnostics, l’ancrage des pratiques et les retours d’expérience.",
    question: "À quelle fréquence préparez-vous un débrief après une activité ?",
    instruction: "Choisissez la fréquence qui vous correspond.",
    options: ["Jamais", "Rarement", "Parfois", "Souvent", "Toujours"],
    demoKind: "choice",
    image: "/images/brivia-quiz-authoring.jpg",
    imageAlt: "Un formateur prépare le déroulé d’une activité pédagogique",
    bestFor: [
      { title: "Diagnostiquer une habitude", text: "Situez une pratique avant la formation." },
      { title: "Mesurer l’ancrage", text: "Vérifiez si un nouveau comportement s’installe." },
      { title: "Adapter un programme", text: "Repérez les pratiques déjà maîtrisées." },
    ],
    capabilities: [
      { title: "Niveaux personnalisables", text: "Ajustez les libellés à la période observée." },
      { title: "Réponse ordonnée", text: "Conservez une lecture naturelle de faible à forte fréquence." },
      { title: "Vue de groupe", text: "Repérez immédiatement les habitudes dominantes." },
      { title: "Historique exploitable", text: "Comparez les résultats dans le temps." },
    ],
    tips: ["Précisez la période observée.", "Évitez les adverbes ambigus.", "Gardez des intervalles cohérents."],
    related: ["likert-scale", "ranking", "single-choice"],
  },
  {
    slug: "star-rating",
    title: "Question de notation par étoiles",
    navTitle: "Notation par étoiles",
    mode: "Sondage",
    description: "Recueillez une appréciation rapide grâce à un code visuel immédiatement compris.",
    detail: "La notation par étoiles convient aux retours à chaud. Elle donne une première lecture simple, à compléter si besoin par une question ouverte.",
    question: "Comment évaluez-vous l’utilité de cette session ?",
    instruction: "Attribuez une note.",
    options: ["1", "2", "3", "4", "5"],
    demoKind: "stars",
    image: "/images/brivia-group-energy.jpg",
    imageAlt: "Des participants réagissent positivement pendant un atelier",
    bestFor: [
      { title: "Retour à chaud", text: "Collectez un ressenti juste après l’activité." },
      { title: "Évaluer une ressource", text: "Demandez une appréciation simple d’un contenu." },
      { title: "Ouvrir un commentaire", text: "Utilisez la note pour déclencher une question de suivi." },
    ],
    capabilities: [
      { title: "Nombre d’étoiles", text: "Définissez la valeur maximale adaptée au contexte." },
      { title: "Geste immédiat", text: "La réponse demande très peu d’effort." },
      { title: "Moyenne et distribution", text: "Lisez le niveau global et la dispersion." },
      { title: "Export des réponses", text: "Reliez la note aux autres retours de session." },
    ],
    tips: ["Expliquez ce que signifie la meilleure note.", "Gardez la même échelle dans un questionnaire.", "Ajoutez une question ouverte pour comprendre la note."],
    related: ["open-text", "nps-scale", "likert-scale"],
  },
  {
    slug: "open-text",
    title: "Question ouverte",
    navTitle: "Question ouverte",
    mode: "Sondage",
    description: "Laissez les participants formuler une idée, un besoin ou un retour avec leurs propres mots.",
    detail: "La question ouverte révèle ce que vos options n’avaient pas prévu. Elle complète efficacement une note, un vote ou une échelle par une explication qualitative.",
    question: "Quelle amélioration rendrait cette formation plus utile ?",
    instruction: "Rédigez une réponse concise.",
    options: ["Votre réponse"],
    demoKind: "text",
    image: "/images/brivia-learner-session.jpg",
    imageAlt: "Un apprenant rédige une réponse pendant une session professionnelle",
    bestFor: [
      { title: "Comprendre une note", text: "Demandez la raison derrière une évaluation." },
      { title: "Faire émerger des idées", text: "Recueillez des propositions non prévues à l’avance." },
      { title: "Identifier un besoin", text: "Laissez chacun nommer son principal obstacle." },
    ],
    capabilities: [
      { title: "Longueur encadrée", text: "Définissez un minimum et un maximum de caractères." },
      { title: "Expression libre", text: "Aucune option ne limite la formulation." },
      { title: "Lecture après session", text: "Retrouvez chaque verbatim dans les résultats." },
      { title: "Export qualitatif", text: "Poursuivez le tri et l’analyse dans vos outils." },
    ],
    tips: ["Posez une question précise.", "Demandez une seule chose à la fois.", "Annoncez la longueur de réponse attendue."],
    related: ["star-rating", "short-answer", "nps-scale"],
  },
  {
    slug: "nps-scale",
    title: "Question à échelle NPS",
    navTitle: "Échelle NPS",
    mode: "Sondage",
    description: "Mesurez l’intention de recommandation sur une échelle standard de 0 à 10.",
    detail: "L’échelle NPS fournit un indicateur de recommandation familier aux équipes expérience client et formation. Brivia collecte les réponses, puis vous laisse conduire l’analyse adaptée.",
    question: "Recommanderiez-vous cette formation à un collègue ?",
    instruction: "Choisissez une note de 0 à 10.",
    options: ["Pas du tout probable", "Tout à fait probable"],
    demoKind: "nps",
    image: "/images/brivia-results-debrief.jpg",
    imageAlt: "Une équipe analyse des indicateurs de satisfaction après une formation",
    bestFor: [
      { title: "Suivre la recommandation", text: "Observez la perception globale d’une expérience." },
      { title: "Comparer des sessions", text: "Utilisez la même question sur plusieurs cohortes." },
      { title: "Déclencher un suivi", text: "Complétez la note par une question ouverte." },
    ],
    capabilities: [
      { title: "Échelle de 0 à 10", text: "Respectez le format attendu pour ce type de mesure." },
      { title: "Libellés aux extrêmes", text: "Clarifiez le sens de la note minimale et maximale." },
      { title: "Répartition visible", text: "Repérez les réponses qui nécessitent un suivi." },
      { title: "Données exportables", text: "Conservez les réponses pour votre méthode de calcul." },
    ],
    tips: ["Gardez la formulation stable.", "Posez une question ouverte juste après.", "Analysez les tendances, pas une note isolée."],
    related: ["star-rating", "open-text", "likert-scale"],
  },
];

export const QUESTION_TYPE_BY_SLUG = new Map(
  QUESTION_TYPE_PAGES.map((questionType) => [questionType.slug, questionType]),
);
